### ISSUE TITLE
The bert model reserved all the GPU

### ISSUE THREAD

**Issue by thtang** [IndoNLP/indonlu#35]
Is nvidia V100 with 32 GB ram large enough for loading the Bert model ?

I got an error `RuntimeError: CUDA out of memory. Tried to allocate 120.00 MiB (GPU 0; 31.75 GiB total capacity; 30.32 GiB already allocated; 9.50 MiB free; 30.42 GiB reserved in total by PyTorch)` after the model was loaded in GPU.

There whole GPU is occupied by the model so that I can't feed the tensor into GPU.

**Comment by SamuelCahyawijaya** [comment]
Oh, that is weird, we only use an 11GB GPU for running our experiment. Can you please ensure your GPU occupancy with `nvidia-smi` and perhaps check whether you can fit a smaller model into GPU.

**Comment by thtang** [comment]
Ok I fixed it. It seems that `tokenizer.batch_encode_plus ` in my code induced the errors.
